### ISSUE TITLE
Curro

### ISSUE THREAD

**Issue by amunozeveris** [hossmi/beca-dotnet-2019#45]
Hola Pablo. 

He encontrado un trabajo y empiezo hoy mismo así que ya no podré asistir al curso, lamento las molestias, gracias por todo y mucha suerte en Madrid y suerte a todos los compañeros.

Un saludo.
Alejandro.

**Comment by hossmi** [comment]
Buenas Alejandro!
Enhorabuena por el trabajo, suerte y a tope con ello!

Un saludo.
